export const grades = [
  '1st',
  '2nd',
  '3rd',
  '4th',
  '5th',
  '6th',
  '7th',
  '8th',
  '9th',
  '10th',
  '11th',
  '12th',
  'Undergraduate',
];
export const formats = ['google doc', 'powerpoint', 'pdf', 'excel', 'word'];
export const resourceTypes = [
  'Assignment',
  'Quiz',
  'Project',
  'Exam',
  'Notes',
  'Study Guide',
  'Syllabus',
  'Textbook',
  'Video',
  'Website',
  'Other',
];
export const subjects = [
  'Math',
  'Science',
  'English',
  'History/Social Studies',
  'Foreign Language',
  'Art',
  'Music',
  'Physical Education',
  'Other',
];
